import { setRequestLocale } from 'next-intl/server';
import { brandName } from '@/lib/brand';
import { routing } from '../../../../i18n/routing';
import Link from 'next/link';
import { BackButton } from '@/components/legal/BackButton';
import { EnglishNotice } from '@/components/legal/EnglishNotice';

type Props = { params: Promise<{ locale: string }> };

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

// Generated from the reviewed B2C legal source (2026-07-26). German is the
// authoritative version; English is provided for information.
function GermanBody() {
  return (
    <>
      <h1>Datenschutzerklärung</h1>
      <p>Stand: 10. August 2026</p>
      <h2>1. Verantwortlicher</h2>
      <p>Verantwortlicher im Sinne der Datenschutz-Grundverordnung (DSGVO) ist:</p>
      <p>AJ GmbH</p>
      <p>Danziger Str. 80</p>
      <p>65191 Wiesbaden</p>
      <p>Deutschland</p>
      <p>Vertreten durch: Dr. Andreas Jahnke</p>
      <p>Datenschutzkontakt: privacy@auswahlbuddy.de</p>
      <h2>2. Geltungsbereich und Mindestalter</h2>
      <p>Diese Datenschutzerklärung gilt für die Website und den Fotoauswahldienst AuswahlBuddy. Der Dienst ist für die persönliche, private oder familiäre Fotoverwaltung bestimmt.</p>
      <p>Die Nutzung setzt ein Mindestalter von 16 Jahren voraus; das entspricht der Altersgrenze für die eigene Einwilligung nach Art. 8 DSGVO in Deutschland. Ein kostenpflichtiger Vertrag kann nur von Personen ab 18 Jahren oder mit Zustimmung eines gesetzlichen Vertreters geschlossen werden. Beide Angaben bestätigst du selbst; wir erheben zur Altersprüfung keine weiteren Daten. Personen unterhalb der jeweiligen Grenze dürfen auf privaten Fotos und Referenzfotos abgebildet sein.</p>
      <p>Der Nutzer entscheidet selbst, welche privaten Fotos und welche ihm bekannten Personen analysiert werden. AuswahlBuddy darf nicht für berufliche oder gewerbliche Zwecke, zur öffentlichen Personensuche, zur Überwachung oder zur Identifizierung unbekannter Personen verwendet werden. Für Referenzfotos bestätigt der Nutzer einmal je Analysevorgang, dass die jeweils abgebildete Person oder – soweit erforderlich – eine hierzu berechtigte Person der beschriebenen Verwendung zugestimmt hat.</p>
      <h2>3. Aufruf der Website und technische Protokolldaten</h2>
      <p>Beim Aufruf der Website werden technisch erforderliche Daten verarbeitet, insbesondere IP-Adresse, Zeitpunkt, aufgerufene Adresse, HTTP-Status, übertragene Datenmenge, Referrer-Informationen, Browser-/Geräteinformationen und technische Fehlerdaten. Die Verarbeitung ist erforderlich, um die Website auszuliefern, Angriffe und Missbrauch abzuwehren und die Stabilität zu gewährleisten.</p>
      <p>Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. f DSGVO. Unser berechtigtes Interesse besteht im sicheren und zuverlässigen Betrieb des Dienstes. Empfänger ist insbesondere unser Hostinganbieter Vercel Inc. einschließlich seiner Unterauftragsverarbeiter.</p>
      <p>Reguläre Speicherdauer der von uns zugänglichen Hosting-/Sicherheitsprotokolle: 30 Tage. Bei Sicherheitsvorfällen können relevante Daten bis zur Aufklärung und Durchsetzung oder Abwehr von Ansprüchen länger gespeichert werden.</p>
      <h2>4. KI-gestützte Fotoauswahl</h2>
      <h3>4.1 Verarbeitete Daten und Ablauf</h3>
      <p>Wenn du eine Fotoauswahl startest, wählst du Fotos auf deinem Endgerät aus. AuswahlBuddy erzeugt im Browser verkleinerte JPEG-Vorschaubilder mit maximal 512 × 512 Pixeln. Hochauflösende Originaldateien werden nicht an unseren KI-Anbieter übertragen und verbleiben auf deinem Endgerät. Die spätere Download-/ZIP-Datei wird lokal in deinem Browser erzeugt.</p>
      <p>Für die Analyse verarbeiten wir die Vorschaubilder, eine technische Vorgangskennung und – soweit für die Sortierung erforderlich – ausgewählte Metadaten wie Aufnahmedatum und Kameramodell. Wenn die optionale Personenfunktion verwendet wird, verarbeiten wir zusätzlich je gesuchter Person ein Referenzfoto und eine neutrale, möglichst nicht namensbezogene Kennzeichnung wie „Person A“. Klarnamen werden nicht an Google übermittelt. Enthält ein Foto GPS-Koordinaten, übermitteln wir diese in <strong>gerundeter Form</strong> mit, damit die KI daraus einen Ortsnamen ableiten kann; Einzelheiten und der Grund für die Rundung stehen in Abschnitt 6.</p>
      <p>Die Vorschaubilder werden über unsere technische Infrastruktur an die bezahlte Gemini Developer API von Google übermittelt. Die KI bewertet Bilder anhand der vom Nutzer gewählten Kriterien und erstellt einen unverbindlichen Auswahlvorschlag. Der Nutzer kann das Ergebnis prüfen, ändern oder verwerfen.</p>
      <h3>4.2 Rollenverteilung, Zwecke und rechtlicher Rahmen</h3>
      <p>Für den Betrieb der Website, Sicherheits- und Missbrauchsprotokolle, Support, Produkt-Updates und eigene Vertragsdaten ist AJ GmbH datenschutzrechtlich Verantwortlicher. Die jeweiligen Zwecke und Rechtsgrundlagen werden in den betreffenden Abschnitten dieser Datenschutzerklärung beschrieben.</p>
      <p>Für die vom Nutzer ausgewählten Foto- und Referenzinhalte, Metadaten und Analyseergebnisse verarbeitet AJ GmbH die Daten ausschließlich nach der durch den Nutzer ausgelösten Weisung und nur zur Durchführung des konkreten privaten Analysevorgangs. AJ GmbH verfolgt mit diesen Inhalten keine eigenen Zwecke, nutzt sie nicht für Werbung oder Modelltraining und ist insoweit als Auftragsverarbeiter ausgestaltet. Der Nutzer bestimmt die Fotos, die gesuchten Personen, die Auswahlkriterien und den privaten Zweck. Die ergänzenden Auftragsverarbeitungsbedingungen sind Bestandteil der Nutzungsbedingungen.</p>
      <p>Soweit der Nutzer Fotos ausschließlich im Rahmen persönlicher oder familiärer Tätigkeiten verarbeitet, fällt seine eigene Verarbeitung unter die Haushaltsausnahme des Art. 2 Abs. 2 Buchst. c DSGVO. Diese Ausnahme gilt nicht für AJ GmbH und die von uns eingesetzten technischen Dienstleister; wir bleiben insbesondere an die für Auftragsverarbeiter geltenden Datenschutz- und Sicherheitsanforderungen gebunden. AuswahlBuddy trifft keine ausschließlich automatisierte Entscheidung mit rechtlicher oder vergleichbar erheblicher Wirkung im Sinne von Art. 22 DSGVO.</p>
      <h3>4.3 Referenzfotos und biometrischer Personenabgleich</h3>
      <p>Wenn die optionale Personenfunktion aktiviert wird, wird das Gesicht auf einem Referenzfoto mit Gesichtern in den ausgewählten privaten Fotos verglichen, um eine zuvor bestimmte und dem Nutzer bekannte Person wiederzufinden. Bei diesem technischen Vergleich können biometrische Daten zum Zweck der eindeutigen Wiedererkennung entstehen.</p>
      <p>AJ GmbH verarbeitet die Foto- und biometrischen Inhalte dabei ausschließlich im Auftrag des Nutzers und nach dessen dokumentierter Weisung. AuswahlBuddy holt keine eigenständige Einwilligung der abgebildeten Person ein. Der Nutzer darf die Funktion nur im privaten oder familiären Umfeld einsetzen und muss zur Verwendung jedes Referenzfotos berechtigt sein. Er muss insbesondere sicherstellen, dass die betroffene Person selbst oder – soweit sie nicht selbst wirksam zustimmen kann – eine hierzu berechtigte Person der vorübergehenden KI-gestützten Wiedererkennung und der dafür erforderlichen technischen Übermittlung zugestimmt hat.</p>
      <p>Für alle Referenzfotos, die innerhalb eines Analysevorgangs über das gemeinsame Upload-Feld bereitgestellt werden, genügt eine einzige aktive Sammelbestätigung. Eine separate Bestätigung je Foto oder Person, eine Altersangabe zur abgebildeten Person sowie ein schriftlicher oder hochzuladender Einwilligungsnachweis werden nicht verlangt. Die Bestätigung darf nicht vorausgewählt sein und muss vor der Übermittlung der Referenzfotos erfolgen.</p>
      <p>Die Sammelbestätigung ist eine vertragliche Zusicherung des Nutzers. Wir protokollieren lediglich Zeitpunkt, Fassung des Bestätigungstextes und eine technische Vorgangskennung; Namen, Kontaktdaten, Verwandtschaftsverhältnisse oder Einwilligungsnachrichten der abgebildeten Personen werden nicht verlangt. Der technische Bestätigungsnachweis wird für 30 Tage gespeichert und nur bei einem konkreten Sicherheits-, Missbrauchs- oder Rechtsfall länger aufbewahrt.</p>
      <p>Referenzfotos, vorübergehende Merkmalsdarstellungen und Zuordnungsergebnisse werden bei AJ GmbH nur für den laufenden Analysevorgang verarbeitet und danach aus der Anwendungsumgebung gelöscht. Wir erstellen keine dauerhaften Gesichts-Templates, Embeddings, Personendatenbanken oder wiederverwendbaren Personentags. Eine technisch mögliche Aufbewahrung bei Google ist in Abschnitt 5 beschrieben und kann die Dauer des Analysevorgangs überschreiten.</p>
      <p>Sollte der KI-Anbieter seine Bedingungen so ändern, dass die in Abschnitt 5 beschriebenen Zusagen für diese Inhalte nicht mehr gelten, stellen wir die Personenfunktion ein, bevor die Änderung wirksam wird. Wegen der besonderen Kategorie dieser Daten setzen wir sie in diesem Fall nicht unter geänderten Bedingungen fort.</p>
      <p>Ob und in welchem Umfang die Personenfunktion verfügbar ist, richtet sich nach den Nutzungsbedingungen. Auf die in diesem Abschnitt beschriebene Verarbeitung und die dort zugesagten Schutzmaßnahmen hat das keinen Einfluss.</p>
      <p>Die Funktion darf nur zum Wiederfinden einer zuvor bestimmten, einwilligenden Person in den vom Nutzer selbst ausgewählten privaten Fotos verwendet werden. Unzulässig sind insbesondere die Identifizierung unbekannter Personen, Abgleiche mit öffentlichen oder fremden Bildbeständen, Überwachung, Strafverfolgungs- oder Sicherheitszwecke sowie die Ableitung ethnischer Herkunft, Religion, Gesundheit, politischer Ansichten, sexueller Orientierung, Emotionen oder anderer sensibler Eigenschaften.</p>
      <h3>4.4 Widerspruch, Rücknahme der Zustimmung und Anfragen abgebildeter Personen</h3>
      <p>Eine abgebildete Person kann dem Nutzer mitteilen, dass ihr Referenzfoto künftig nicht mehr verwendet werden darf. Der Nutzer muss diese Entscheidung beachten und darf das Foto nicht erneut hochladen. Betroffene Personen können sich außerdem an unseren Datenschutzkontakt wenden. Da wir weder Namen noch dauerhafte Gesichtsprofile speichern, ist eine nachträgliche Zuordnung regelmäßig nur anhand von Zeitpunkt und technischer Vorgangskennung möglich. Bereits an Google übermittelte Sicherheits- oder Missbrauchsprotokolle können nach den in Abschnitt 5 beschriebenen Regeln bis zum Ablauf der dortigen Frist fortbestehen.</p>
      <p>Bitte lade keine Ausweisdokumente, medizinischen Aufnahmen, intimen Inhalte oder sonstigen hochsensiblen Bilder hoch. Werden solche Inhalte dennoch hochgeladen, werden sie technisch wie andere Vorschaubilder verarbeitet; eine gesonderte fachliche oder inhaltliche Auswertung ist nicht vorgesehen.</p>
      <h2>5. Google Gemini Developer API</h2>
      <p>Für die KI-Analyse setzen wir einen kostenpflichtigen Zugang zur Gemini Developer API ein. Vertragspartner für Kunden mit deutscher Rechnungsadresse ist nach den aktuellen Google-Vertragsinformationen grundsätzlich Google Cloud EMEA Limited, 70 Sir John Rogerson’s Quay, Dublin 2, Irland, sofern im konkreten Cloud-Vertrag nichts anderes vereinbart wurde.</p>
      <p>Nach den Bedingungen für Paid Services verwendet Google die übermittelten Eingaben, Dateien und Antworten nicht zur Verbesserung oder zum Training seiner Modelle. Wir aktivieren keine freiwillige Freigabe von Logs oder Datasets an Google und verwenden die Daten nicht zum Modelltraining.</p>
      <p>Maßgeblich ist der mit dem KI-Anbieter geschlossene Auftragsverarbeitungsvertrag in der zum Zeitpunkt der jeweiligen Verarbeitung geltenden Fassung. KI-Anbieter können ihre Bedingungen für die Zukunft ändern. Sollte ein Anbieter seine Bedingungen so ändern, dass die in diesem Abschnitt beschriebenen Zusagen — insbesondere der Ausschluss des Modelltrainings und die begrenzte Aufbewahrung — nicht mehr gelten, beenden wir den Einsatz dieses Anbieters, bevor die Änderung für uns wirksam wird, oder wechseln zu einem anderen Anbieter. Diese Datenschutzerklärung passen wir vorher an. Für bereits abgeschlossene Verarbeitungen bleibt die zum Verarbeitungszeitpunkt beschriebene Fassung maßgeblich.</p>
      <p>Google kann Eingaben und Ausgaben für Sicherheits-, Missbrauchserkennungs- und gesetzliche Zwecke für einen begrenzten Zeitraum aufbewahren. Nach der derzeitigen Google-Dokumentation kann diese Aufbewahrung bis zu 55 Tage betragen. Je nach eingesetzter API-Funktion können zusätzliche Speicherungen entstehen. Deshalb verwenden wir keine File API, keine dauerhaft gespeicherten Datasets und kein dauerhaftes Context Caching; bei zustandsbehafteten API-Funktionen deaktivieren wir die Speicherung, soweit dies technisch möglich ist.</p>
      <p>Google kann Daten in Ländern verarbeiten, in denen Google oder seine Unterauftragsverarbeiter Einrichtungen betreiben. Grundlage sind der einschlägige Auftragsverarbeitungsvertrag, die Standardvertragsklauseln der Europäischen Kommission und/oder ein anwendbarer Angemessenheitsbeschluss. Trotz dieser Schutzmechanismen können bei Verarbeitungen außerhalb des Europäischen Wirtschaftsraums Restrisiken bestehen, insbesondere behördliche Zugriffsrechte nach dem Recht des Empfängerstaats.</p>
      <h2>6. Ortsnamen aus GPS-Daten</h2>
      <p>Viele Kameras und Smartphones schreiben den Aufnahmeort als GPS-Koordinaten in die Bilddatei. Damit du deine Auswahl nach Orten sortieren kannst, leitet die KI aus diesen Koordinaten einen Ortsnamen ab („Lissabon, Portugal“). Der Ortsname wird in der Ergebnisübersicht angezeigt und kann als Ordnerstruktur in die Download-Datei übernommen werden.</p>
      <p>Die Ableitung erfolgt bei demselben KI-Anbieter, der ohnehin die Bildanalyse durchführt (Abschnitt 5). Wir setzen dafür <strong>keinen zusätzlichen Geokodierungsdienst</strong> und keinen weiteren Empfänger ein.</p>
      <p><strong>Die Koordinaten werden vor der Übermittlung gerundet.</strong> Wir übermitteln sie auf zwei Nachkommastellen gekürzt; das entspricht einem Raster von rund einem Kilometer. Das genügt, um einen Ort oder eine Region zu benennen, reicht aber nicht aus, um eine Wohnung, ein Hotelzimmer oder eine Schule zu bestimmen. Die vollständigen Koordinaten verlassen dein Endgerät nicht — sie stehen nur in der lokal erzeugten Download-Datei, die ebenfalls auf deinem Gerät bleibt.</p>
      <p>Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. b DSGVO: die Ortszuordnung ist Teil der von dir beauftragten Auswahlleistung. Enthält ein Foto keine GPS-Daten, wird für dieses Foto nichts übermittelt und kein Ortsname gebildet. Möchtest du generell keine Ortsdaten übermitteln, entferne die GPS-Daten vor dem Hochladen aus deinen Fotos oder schalte die Standortspeicherung in deiner Kamera-App ab.</p>
      <p>Die Koordinaten werden von AJ GmbH nicht dauerhaft gespeichert. Für die Aufbewahrung beim KI-Anbieter gilt Abschnitt 5.</p>
      <h2>7. Optionaler Cloud-Import und -Export</h2>
      <p>Derzeit ist <strong>Dropbox</strong> als Cloud-Anbieter freigeschaltet, sowohl für den Import von Fotos als auch für den Export deiner Auswahl. Weitere Anbieter (etwa Microsoft OneDrive) sind vorbereitet, aber nicht aktiv; bevor wir einen davon freischalten, benennen wir ihn an dieser Stelle.</p>
      <p>Die Autorisierung erfolgt über OAuth. Wir fragen die Berechtigungen getrennt und erst dann ab, wenn du den jeweiligen Vorgang auslöst: für den <strong>Export</strong> ausschließlich das Schreibrecht, für den <strong>Import</strong> das Leserecht auf Datei- und Ordnerinformationen sowie Dateiinhalte. Damit du deine Fotos aus beliebigen Ordnern auswählen kannst, umfasst das Leserecht deinen gesamten Dropbox-Bestand und nicht nur einen App-Ordner. Wir sehen davon nur, was du im Auswahldialog tatsächlich öffnest und auswählst; wir durchsuchen deinen Bestand nicht selbständig und legen kein Verzeichnis davon an.</p>
      <p>Die Dateien fließen direkt zwischen deinem Browser und Dropbox — nicht über unsere Server. OAuth-Tokens werden nur für die Dauer des Vorgangs bzw. der Browser-Sitzung im Arbeitsspeicher verwendet und nicht dauerhaft gespeichert. Du kannst die Verbindung jederzeit in den Sicherheitseinstellungen deines Dropbox-Kontos widerrufen.</p>
      <p>Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. b DSGVO. Für die Verarbeitung in deinem Cloud-Konto gelten ergänzend die Datenschutzbedingungen des jeweiligen Cloud-Anbieters. Bitte prüfe die angezeigten Zugriffsrechte vor der Freigabe.</p>
      <h2>8. Feedback, Support und Produkt-Updates</h2>
      <p>Wenn du uns Feedback oder eine Supportanfrage sendest, verarbeiten wir deine Kontaktdaten, den Nachrichtentext und erforderliche technische Informationen, um die Anfrage zu bearbeiten und den Dienst zu verbessern. Rechtsgrundlage ist je nach Inhalt Art. 6 Abs. 1 Buchst. b oder f DSGVO. Unser berechtigtes Interesse liegt in der Bearbeitung von Anfragen und der Fehlerbehebung.</p>
      <p>Reguläre Speicherdauer für Feedback-/Supportdaten: 12 Monate nach Abschluss, sofern keine gesetzlichen Aufbewahrungspflichten oder Rechtsansprüche eine längere Speicherung erfordern.</p>
      <p>Wenn du Produkt-Updates abonnierst, verarbeiten wir deine E-Mail-Adresse auf Grundlage deiner Einwilligung nach Art. 6 Abs. 1 Buchst. a DSGVO und § 7 Abs. 2 UWG. Soweit eingesetzt, verwenden wir ein Double-Opt-in-Verfahren. Du kannst deine Einwilligung jederzeit über den Abmeldelink oder durch Nachricht an uns widerrufen. Den Nachweis der Einwilligung können wir für die Dauer gesetzlicher Verjährungsfristen speichern.</p>
      <p>Für die Speicherung von Feedback, E-Mail-Adressen und Missbrauchszählern setzen wir Upstash, Inc. ein; die Datenbank ist auf eine EU-Region beschränkt. Für den Versand von E-Mails — insbesondere Bestätigungs- und Anmelde-Mails zum Nutzerkonto sowie die Weiterleitung von Feedback an unser Postfach — setzen wir Resend, Inc. (USA) ein, das seinerseits Amazon Simple Email Service als Unterauftragsverarbeiter nutzt. Mit beiden Anbietern bestehen Auftragsverarbeitungsverträge nach Art. 28 DSGVO; für Übermittlungen in die USA dienen EU-Standardvertragsklauseln als Grundlage.</p>
      <h2>8a. Zahlungsabwicklung</h2>
      <p><strong>Derzeit ist nur der kostenlose Tarif freigeschaltet; es findet keine Zahlungsabwicklung statt.</strong> Sobald du einen kostenpflichtigen Tarif buchst, wickeln wir die Zahlung über Stripe Payments Europe, Ltd. (Irland) ab. Du gibst deine Zahlungsdaten direkt bei Stripe ein; vollständige Karten- oder Kontodaten erreichen uns nicht.</p>
      <p>Wir verarbeiten in diesem Zusammenhang die Kennung des Bezahlvorgangs, den gebuchten Tarif, den Betrag, den Zahlungsstatus und den Zeitpunkt sowie die von Stripe an uns zurückgemeldeten Rechnungsdaten. Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. b DSGVO (Vertragserfüllung) und, soweit es um Rechnungs- und Buchungsunterlagen geht, Art. 6 Abs. 1 Buchst. c DSGVO in Verbindung mit den handels- und steuerrechtlichen Aufbewahrungspflichten.</p>
      <p>Stripe ist insoweit eigenständig Verantwortlicher für die Zahlungsabwicklung und die Erfüllung eigener aufsichtsrechtlicher Pflichten; es gilt ergänzend die Datenschutzerklärung von Stripe.</p>
      <h2>9. Cookies, lokale Speicherung und Reichweitenmessung</h2>
      <p>Wir verwenden technisch erforderliche Cookies oder ähnliche Speicherzugriffe nur, soweit sie für die von dir ausdrücklich gewünschte Funktion erforderlich sind. Rechtsgrundlage für den Zugriff auf dein Endgerät ist § 25 Abs. 2 TDDDG; die anschließende Verarbeitung personenbezogener Daten stützen wir auf Art. 6 Abs. 1 Buchst. b oder f DSGVO.</p>
      <h3>9.1 Eigene Nutzungs- und Kampagnenmessung</h3>
      <p>Um zu verstehen, an welcher Stelle der Dienst verständlich ist und wo Nutzer abbrechen, erfassen wir eigene Ereignisse — etwa den Aufruf der Startseite, den Beginn einer Fotoauswahl, den Abschluss oder Fehlschlag einer Analyse und den Download des Ergebnisses. Die Ereignisse werden ausschließlich an unseren eigenen Endpunkt auf derselben Domain gesendet und bei unserem Dienstleister Upstash in der EU gespeichert. Wir binden dafür keine Zähl-Pixel, Tags oder Skripte Dritter ein.</p>
      <p>Zu einem Ereignis speichern wir eine zufällige Sitzungskennung, Geräteklasse (Mobil, Tablet, Desktop), Betriebssystem- und Browserfamilie, die Sprachfassung, eine grobe Größenklasse der ausgewählten Fotomenge sowie — wenn du über eine von uns geschaltete Anzeige gekommen bist — die Kampagnenkennzeichen aus der aufgerufenen Adresse (die sogenannten UTM-Parameter). <strong>Nicht</strong> gespeichert werden Dateinamen, Bildinhalte, Standortdaten und E-Mail-Adressen.</p>
      <p>Für diese Messung greifen wir nicht auf dein Endgerät zu. Die Sitzungskennung besteht nur im Arbeitsspeicher deines Browsers und endet, wenn du die Seite schließt; sie wird weder in einem Cookie noch im lokalen Speicher deines Browsers abgelegt. Deshalb ist hierfür weder eine Einwilligung nach § 25 TDDDG noch ein Cookie-Banner erforderlich. Der Preis dieser Zurückhaltung ist, dass wir wiederkehrende Besucher nicht wiedererkennen — das ist beabsichtigt.</p>
      <p>Von Werbenetzwerken vergebene Klick-Kennungen (etwa <span className="font-mono">gclid</span> oder <span className="font-mono">fbclid</span>), die beim Aufruf über eine Anzeige an der Adresse hängen können, speichern wir nicht und werten wir nicht aus.</p>
      <p>Wenn du in deinem Nutzerkonto angemeldet bist, ordnen wir diese Ereignisse zusätzlich einer aus deiner Konto-Kennung abgeleiteten Pseudonymkennung zu. Nur dadurch können wir erkennen, ob der Dienst ein zweites Mal genutzt wird. Diese Zuordnung erfolgt nicht, solange du nicht angemeldet bist.</p>
      <p>Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. f DSGVO. Unser berechtigtes Interesse besteht darin, Verständlichkeit, technische Qualität und Wirtschaftlichkeit des Dienstes in datensparsamer Form beurteilen zu können, ohne dafür Tracking-Dienste Dritter einzusetzen. Du kannst dieser Verarbeitung nach Art. 21 DSGVO widersprechen; wende dich dazu an unseren Datenschutzkontakt. Zu den Speicherfristen siehe Abschnitt 11.</p>
      <h3>9.2 Reichweitenmessung durch Vercel</h3>
      <p>Für eine aggregierte Reichweitenmessung kann Vercel Web Analytics in einer cookielosen Konfiguration eingesetzt werden. Nach unserer Konfiguration werden keine geräteübergreifenden oder websiteübergreifenden Nutzerprofile erstellt. Die uns bereitgestellten Auswertungen sind aggregiert. Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. f DSGVO; unser berechtigtes Interesse besteht darin, Nutzung und technische Qualität des Dienstes in datensparsamer Form zu verstehen.</p>
      <h3>9.3 Keine Statistik- und Marketingdienste Dritter</h3>
      <p>Google Analytics, Google Ads, Meta-Pixel und andere nicht erforderliche Statistik- oder Marketingdienste sind nicht aktiv. Wir haben uns bewusst dagegen entschieden, sie für die Auswertung unserer Anzeigenkampagnen einzusetzen, und werten diese stattdessen über die in Abschnitt 9.1 beschriebene eigene Messung aus. Sollten wir solche Dienste später einsetzen, werden sie erst nach deiner freiwilligen Einwilligung aktiviert und diese Datenschutzerklärung wird vorab aktualisiert.</p>
      <h2>10. Empfänger und Auftragsverarbeiter</h2>
      <p>Je nach Nutzung können insbesondere folgende Empfänger Daten verarbeiten:</p>
      <p>Google Cloud EMEA Limited und Google-Unterauftragsverarbeiter – KI-Analyse über die bezahlte Gemini Developer API;</p>
      <p>Vercel Inc. und Unterauftragsverarbeiter – Hosting, Auslieferung, Sicherheitsprotokolle und gegebenenfalls cookielose Reichweitenmessung;</p>
      <p>Upstash, Inc. und Unterauftragsverarbeiter – Feedback, Update-Anmeldungen, Missbrauchszähler und die Ereignisse der eigenen Nutzungsmessung nach Abschnitt 9.1, in der EU-Region;</p>
      <p>Supabase, Inc. und Unterauftragsverarbeiter – Konten, Authentifizierung und Vorgangsdaten (siehe Abschnitt 15);</p>
      <p>Resend, Inc. und Amazon Web Services – Versand von Konto- und Feedback-E-Mails;</p>
      <p>Stripe Payments Europe, Ltd. – Zahlungsabwicklung, sobald du einen kostenpflichtigen Tarif buchst (siehe Abschnitt 8a);</p>
      <p>Dropbox – nur wenn du den Cloud-Import oder -Export nutzt; weitere Cloud-Anbieter derzeit nicht aktiv;</p>
      <p>IT-, Sicherheits-, Rechts- oder Behördenstellen, soweit dies zur Erfüllung gesetzlicher Pflichten oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist.</p>
      <p>Mit Auftragsverarbeitern schließen wir Verträge nach Art. 28 DSGVO. Bei Drittlandtransfers verwenden wir, soweit erforderlich, Angemessenheitsbeschlüsse, EU-Standardvertragsklauseln und ergänzende Schutzmaßnahmen.</p>
      <h2>11. Speicherdauer</h2>
      <p>Hochauflösende Originalfotos: keine Übermittlung an Google und keine Speicherung durch AJ GmbH;</p>
      <p>Vorschaubilder bei AJ GmbH: keine dauerhafte Speicherung in einer Anwendungsdatenbank; Verarbeitung nur für die Dauer des Vorgangs und technisch unvermeidbare Kurzzeitspeicherung;</p>
      <p>Vorschaubilder und Antworten bei Google: nach aktueller Dokumentation für Sicherheits-/Missbrauchszwecke bis zu 55 Tage, sofern keine kürzere Zero-Data-Retention-Konfiguration verbindlich greift;</p>
      <p>Hosting-/Sicherheitslogs: 30 Tage, siehe Abschnitt 3;</p>
      <p>Feedback/Support und Update-Anmeldungen: gemäß Abschnitt 8;</p>
      <p>Gerundete GPS-Koordinaten zur Ortsbestimmung: keine Speicherung bei AJ GmbH; beim KI-Anbieter gelten dieselben Fristen wie für die Vorschaubilder;</p>
      <p>Ereignisse der eigenen Nutzungsmessung nach Abschnitt 9.1: 90 Tage in der Einzelform, danach ausschließlich in aggregierter Form ohne Sitzungs- oder Kontobezug;</p>
      <p>Zahlungs- und Rechnungsdaten nach Abschnitt 8a: für die Dauer der handels- und steuerrechtlichen Aufbewahrungsfristen, in der Regel bis zu zehn Jahre;</p>
      <p>Technische Bestätigung der Referenzfoto-Berechtigung: ohne Referenzfoto, Namen oder Kontaktdaten für 30 Tage; längere Speicherung nur bei einem konkreten Sicherheits-, Missbrauchs- oder Rechtsfall.</p>
      <h2>12. Datensicherheit</h2>
      <p>Wir treffen technische und organisatorische Maßnahmen, die dem Risiko der Verarbeitung angemessen sind. Dazu gehören insbesondere verschlüsselte Übertragung, Zugriffsbeschränkungen, getrennte Schlüssel- und Rechteverwaltung, Datenminimierung, Missbrauchsbegrenzung, Protokollierung sicherheitsrelevanter Ereignisse und regelmäßige Überprüfung der eingesetzten Dienstleister. Ein absoluter Schutz bei der Datenübertragung oder Speicherung kann jedoch nicht garantiert werden.</p>
      <h2>13. Deine Rechte</h2>
      <p>Nach Maßgabe der gesetzlichen Voraussetzungen hast du insbesondere das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Erteilte Einwilligungen kannst du jederzeit mit Wirkung für die Zukunft widerrufen. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung bleibt unberührt.</p>
      <p>Bitte richte Anfragen an den unter Abschnitt 1 genannten Datenschutzkontakt. Da wir Fotos nicht dauerhaft speichern und regelmäßig keine Identitätsdaten zu einem einzelnen Analysevorgang vorhalten, können wir zur Zuordnung einer Anfrage zusätzliche Angaben zum Zeitpunkt und Ablauf des Vorgangs benötigen. Wir werden keine zusätzlichen Daten allein zum Zweck der Identifizierung speichern, wenn dies nicht erforderlich ist.</p>
      <p>Du hast außerdem das Recht, dich bei einer Datenschutzaufsichtsbehörde zu beschweren. Für AJ GmbH ist regelmäßig zuständig:</p>
      <p>Der Hessische Beauftragte für Datenschutz und Informationsfreiheit</p>
      <p>Wilhelmstraße 7</p>
      <p>65185 Wiesbaden</p>
      <p>Deutschland</p>
      <h2>14. Widerspruch gegen Verarbeitungen nach Art. 6 Abs. 1 Buchst. f DSGVO</h2>
      <p>Du kannst aus Gründen, die sich aus deiner besonderen Situation ergeben, jederzeit gegen Verarbeitungen Widerspruch einlegen, die wir auf Art. 6 Abs. 1 Buchst. f DSGVO stützen. Wir verarbeiten die betreffenden Daten dann nicht mehr, es sei denn, wir können zwingende schutzwürdige Gründe nachweisen, die deine Interessen, Rechte und Freiheiten überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.</p>
      <h2>15. Konto und Nutzerregistrierung</h2>
      <p>Wenn du ein Nutzerkonto erstellst, verarbeiten wir deine E-Mail-Adresse, dein verschlüsseltes Passwort, die gewählte Sprache (Spracheinstellung) sowie Zeitpunkt und Nachweis der erteilten Einwilligung in Datenschutzerklärung und Nutzungsbedingungen. Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. b DSGVO (Vertragserfüllung).</p>
      <h3>15.1 Anonymes Konto beim Start einer Analyse</h3>
      <p>Jede Analyse läuft technisch gegen einen benannten Vorgang, damit Fotomengen, Kontingente und Ergebnisse eindeutig zugeordnet werden können. Wenn du eine Analyse startest, ohne angemeldet zu sein, legen wir dafür automatisch ein <strong>anonymes Konto</strong> an. Dabei werden keine Kontaktdaten erhoben: gespeichert werden lediglich eine zufällige Kennung, der Zeitpunkt, die Kennzeichnung als anonym sowie die zum Vorgang gehörenden technischen Daten.</p>
      <p>Rechtsgrundlage ist Art. 6 Abs. 1 Buchst. b DSGVO; ohne diese Zuordnung lässt sich der von dir angestoßene Vorgang nicht durchführen. Ein anonymes Konto erlaubt keine Anmeldung von einem anderen Gerät und geht verloren, wenn du die Browser-Sitzung beendest. Anonyme Konten und die zugehörigen Vorgangsdaten löschen wir turnusmäßig, spätestens 90 Tage nach dem letzten Vorgang. Wenn du dich später registrierst, kannst du deinen Vorgang mit dem neuen Konto fortführen.</p>
      <h3>15.2 Konto und Nutzungsmessung</h3>
      <p>Bist du angemeldet, ordnen wir die Ereignisse aus Abschnitt 9.1 einer aus deiner Konto-Kennung abgeleiteten Pseudonymkennung zu. Wir bilden daraus keine Profile über einzelne Nutzer, sondern werten ausschließlich aus, wie häufig der Dienst insgesamt ein zweites Mal genutzt wird.</p>
      <p>Wir setzen Supabase (Supabase Inc., 970 Trestle Glen Rd, Oakland, CA 94610, USA) als Auftragsverarbeiter für Authentifizierung und Profildatenspeicherung ein. Supabase hostet die Daten auf Servern in der EU-Region Frankfurt (AWS eu-central-1). Mit Supabase besteht ein Auftragsverarbeitungsvertrag nach Art. 28 DSGVO; für Übermittlungen in die USA dienen EU-Standardvertragsklauseln als Grundlage.</p>
      <p>Deine Kontodaten werden gespeichert, solange das Konto besteht. Du kannst dein Konto jederzeit löschen; nach Löschung werden deine Daten innerhalb von 30 Tagen endgültig entfernt. Dein Auskunfts-, Berichtigungs- und Löschungsrecht kannst du jederzeit über unseren Datenschutzkontakt ausüben.</p>
      <h2>16. Änderungen dieser Datenschutzerklärung</h2>
      <p>Wir aktualisieren diese Datenschutzerklärung, wenn sich Funktionen, Dienstleister oder Rechtslage ändern. Maßgeblich ist die jeweils auf der Website veröffentlichte Fassung. Wesentliche Änderungen, die eine neue Einwilligung erfordern, setzen wir nicht ohne diese Einwilligung um.</p>
    </>
  );
}

function EnglishBody() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <EnglishNotice />
      <p>Last updated: 10 August 2026</p>
      <h2>1. Controller</h2>
      <p>The controller within the meaning of the General Data Protection Regulation (GDPR) is:</p>
      <p>AJ GmbH</p>
      <p>Danziger Str. 80</p>
      <p>65191 Wiesbaden</p>
      <p>Germany</p>
      <p>Represented by: Dr Andreas Jahnke</p>
      <p>Privacy contact: privacy@shortlistbuddy.com</p>
      <h2>2. Scope and minimum age</h2>
      <p>This Privacy Policy applies to the website and the ShortlistBuddy photo-selection service. The service is intended for personal, private or family photo management.</p>
      <p>Use requires a minimum age of 16, which corresponds to the age limit for a person’s own consent under Article 8 GDPR in Germany. A paid contract can only be concluded by persons aged 18 or over, or with the consent of a legal guardian. You confirm both yourself; we collect no further data for age verification. Persons below the relevant threshold may appear in private photos and reference photos.</p>
      <p>The user decides which private photos and which known persons are analysed. ShortlistBuddy must not be used for professional or commercial purposes, public person searches, surveillance or identification of unknown persons. For reference photos, the user gives one confirmation per analysis job that each person shown—or, where necessary, a person authorised to act for them—has agreed to the described use.</p>
      <h2>3. Website access and technical log data</h2>
      <p>When the website is accessed, technically necessary data is processed, in particular the IP address, time, requested URL, HTTP status, data volume, referrer information, browser/device information and technical error data. This processing is necessary to deliver the website, prevent attacks and misuse, and maintain stability.</p>
      <p>The legal basis is Article 6(1)(f) GDPR. Our legitimate interest is the secure and reliable operation of the service. Recipients include our hosting provider Vercel Inc. and its subprocessors.</p>
      <p>Regular retention period for hosting/security logs accessible to us: 30 days. Relevant data may be retained for longer where necessary to investigate security incidents or establish, exercise or defend legal claims.</p>
      <h2>4. AI-assisted photo selection</h2>
      <h3>4.1 Data processed and workflow</h3>
      <p>When you start a photo-selection job, you select photos on your device. ShortlistBuddy creates reduced JPEG previews in your browser with a maximum size of 512 × 512 pixels. High-resolution originals are not sent to our AI provider and remain on your device. The later download/ZIP file is created locally in your browser.</p>
      <p>For the analysis, we process the previews, a technical job identifier and, where required for sorting, selected metadata such as capture date and camera model. If the optional Persons feature is used, we additionally process one reference photo for each person sought and a neutral label such as “Person A”, preferably without a real name. Real names are not sent to Google. Where a photo contains GPS coordinates, we send them along in <strong>rounded form</strong> so the AI can derive a place name from them; details and the reason for the rounding are in section 6.</p>
      <p>The previews are transmitted through our technical infrastructure to Google’s paid Gemini Developer API. The AI evaluates the images against criteria selected by the user and creates a non-binding proposed selection. The user can review, modify or reject the result.</p>
      <h3>4.2 Roles, purposes and legal framework</h3>
      <p>AJ GmbH is the controller for website operation, security and abuse logs, support, product updates and its own contractual data. The relevant purposes and legal bases are described in the respective sections of this Privacy Policy.</p>
      <p>For photo and reference content selected by the user, metadata and analysis results, AJ GmbH processes the data solely on the instruction triggered by the user and only to perform the specific private analysis job. AJ GmbH does not pursue its own purposes with this content, does not use it for advertising or model training and is structured as a processor in this respect. The user determines the photos, persons sought, selection criteria and private purpose. The supplementary processing terms form part of the Terms of Use.</p>
      <p>Where the user processes photos solely in the course of personal or household activities, the user’s own processing falls within the household exemption in Article 2(2)(c) GDPR. This exemption does not apply to AJ GmbH or the technical providers we use; we remain subject in particular to the data-protection and security obligations applicable to processors. ShortlistBuddy does not make solely automated decisions producing legal or similarly significant effects within Article 22 GDPR.</p>
      <h3>4.3 Reference photos and biometric person matching</h3>
      <p>If the optional Persons feature is activated, the face in a reference photo is compared with faces in the selected private photos in order to find a previously specified person known to the user. This technical comparison may generate biometric data for the purpose of unique recognition.</p>
      <p>AJ GmbH processes the photo and biometric content solely on the user’s behalf and documented instructions. ShortlistBuddy does not independently collect consent from the person shown. The user may use the feature only in a private or family setting and must be authorised to use each reference photo. In particular, the user must ensure that the person shown—or, where that person cannot validly agree themselves, a person authorised to act for them—has agreed to the temporary AI-assisted recognition and the necessary technical transfer.</p>
      <p>One active collective confirmation is sufficient for all reference photos provided through the common upload field in an analysis job. ShortlistBuddy does not require a separate confirmation for each photo or person, an age declaration for the person shown, or written/uploaded evidence of agreement. The confirmation must not be preselected and must be given before the reference photos are transferred.</p>
      <p>The collective confirmation is a contractual representation by the user. We record only the timestamp, version of the confirmation text and a technical job identifier; we do not request names, contact details, relationships or consent messages relating to the persons shown. The technical confirmation record is retained for 30 days and longer only in a specific security, misuse or legal case.</p>
      <p>Reference photos, temporary feature representations and matching results are processed by AJ GmbH only for the current analysis job and are then deleted from the application environment. We do not create persistent facial templates, embeddings, person databases or reusable person tags. Technically possible retention by Google is described in section 5 and may extend beyond the analysis job.</p>
      <p>Should the AI provider change its terms such that the commitments described in section 5 no longer apply to this content, we will discontinue the Persons feature before the change takes effect. Because of the special category of this data, we will not continue it under changed terms.</p>
      <p>Whether and to what extent the Persons feature is available is governed by the Terms of Use. This has no effect on the processing described in this section or on the safeguards committed to here.</p>
      <p>The feature may be used only to find a previously specified consenting person in private photos selected by the user. It must not be used to identify unknown individuals, search public or third-party image collections, conduct surveillance, support law-enforcement or security purposes, or infer ethnic origin, religion, health, political opinions, sexual orientation, emotions or other sensitive characteristics.</p>
      <h3>4.4 Objection, withdrawal of permission and requests from persons shown</h3>
      <p>A person shown may tell the user that their reference photo must not be used in future. The user must respect that decision and must not upload the photo again. Persons shown may also contact our privacy contact. Because we do not store names or persistent facial profiles, retrospective identification will normally require the approximate time and technical job identifier. Security or abuse logs already transmitted to Google may remain until the period described in section 5 expires.</p>
      <p>Do not upload identity documents, medical images, intimate content or other highly sensitive images. If such content is nevertheless uploaded, it is technically processed like any other preview; no separate professional or substantive analysis is intended.</p>
      <h2>5. Google Gemini Developer API</h2>
      <p>We use a paid Gemini Developer API account for AI analysis. According to Google’s current contracting-entity information, the contracting entity for customers with a German billing address is generally Google Cloud EMEA Limited, 70 Sir John Rogerson’s Quay, Dublin 2, Ireland, unless the specific cloud agreement states otherwise.</p>
      <p>Under the Paid Services terms, Google does not use submitted inputs, files or responses to improve or train its models. We do not enable voluntary sharing of logs or datasets with Google and do not use the data for model training.</p>
      <p>What governs is the data processing agreement concluded with the AI provider, in the version applicable at the time of the relevant processing. AI providers may change their terms for the future. Should a provider change its terms such that the commitments described in this section — in particular the exclusion of model training and the limited retention — no longer apply, we will discontinue that provider before the change takes effect for us, or switch to another provider. We will update this Privacy Policy beforehand. For processing already completed, the version described at the time of processing remains decisive.</p>
      <p>Google may retain inputs and outputs for security, abuse-detection and legal purposes for a limited period. Google’s current documentation states that this may be up to 55 days. Additional retention may arise depending on the API features used. We therefore do not use the File API, permanently stored datasets or persistent context caching, and disable storage for stateful API features where technically possible.</p>
      <p>Google may process data in countries where Google or its subprocessors maintain facilities. The relevant data processing agreement, European Commission Standard Contractual Clauses and/or an applicable adequacy decision provide the transfer basis. Residual risks may remain for processing outside the European Economic Area, particularly statutory access powers in the recipient country.</p>
      <h2>6. Place names from GPS data</h2>
      <p>Many cameras and smartphones write the location of capture into the image file as GPS coordinates. So that you can sort your selection by place, the AI derives a place name from those coordinates (“Lisbon, Portugal”). The place name is shown in the results overview and can be used as the folder structure in the download file.</p>
      <p>This is done by the same AI provider that performs the image analysis anyway (section 5). We use <strong>no additional geocoding service</strong> and no further recipient for it.</p>
      <p><strong>Coordinates are rounded before transmission.</strong> We send them truncated to two decimal places, which corresponds to a grid of roughly one kilometre. That is enough to name a town or region but not enough to identify a home, a hotel room or a school. The full coordinates never leave your device — they appear only in the locally generated download file, which also stays on your device.</p>
      <p>The legal basis is Article 6(1)(b) GDPR: assigning places is part of the selection service you commissioned. If a photo contains no GPS data, nothing is transmitted for that photo and no place name is formed. If you would rather not transmit location data at all, remove the GPS data from your photos before uploading or switch off location recording in your camera app.</p>
      <p>AJ GmbH does not permanently store the coordinates. Retention at the AI provider is governed by section 5.</p>
      <h2>7. Optional cloud import and export</h2>
      <p><strong>Dropbox</strong> is currently enabled as a cloud provider, both for importing photos and for exporting your selection. Other providers (such as Microsoft OneDrive) are prepared but not active; before enabling any of them we will name it at this point.</p>
      <p>Authorisation is performed via OAuth. We request permissions separately and only when you trigger the relevant operation: for <strong>export</strong>, the write permission only; for <strong>import</strong>, read permission for file and folder information and for file content. So that you can pick your photos from any folder, the read permission covers your entire Dropbox rather than just an app folder. We see only what you actually open and select in the picker; we do not search your storage on our own initiative and do not build an index of it.</p>
      <p>Files flow directly between your browser and Dropbox — not through our servers. OAuth tokens are held in memory only for the duration of the transaction or browser session and are not stored permanently. You can revoke the connection at any time in the security settings of your Dropbox account.</p>
      <p>The legal basis is Article 6(1)(b) GDPR. The privacy terms of the relevant cloud provider also apply to processing within your cloud account. Review the displayed permissions before granting access.</p>
      <h2>8. Feedback, support and product updates</h2>
      <p>If you send feedback or a support request, we process your contact details, message and necessary technical information to handle the request and improve the service. Depending on the content, the legal basis is Article 6(1)(b) or (f) GDPR. Our legitimate interest is handling requests and correcting errors.</p>
      <p>Regular retention period for feedback/support data: 12 months after closure, unless statutory retention duties or legal claims require longer storage.</p>
      <p>If you subscribe to product updates, we process your email address based on your consent under Article 6(1)(a) GDPR and section 7(2) of the German Unfair Competition Act. Where used, we apply a double-opt-in procedure. You may withdraw consent at any time through the unsubscribe link or by contacting us. Evidence of consent may be retained for statutory limitation periods.</p>
      <p>We use Upstash, Inc. to store feedback, email addresses and abuse-prevention counters; the database is restricted to an EU region. To send emails — in particular account confirmation and sign-in emails and the forwarding of feedback to our inbox — we use Resend, Inc. (USA), which in turn uses Amazon Simple Email Service as a subprocessor. We have concluded Article 28 GDPR processing agreements with both providers; EU Standard Contractual Clauses provide the basis for transfers to the USA.</p>
      <h2>8a. Payment processing</h2>
      <p><strong>At present only the free plan is enabled; no payment processing takes place.</strong> Once you book a paid plan, we process the payment through Stripe Payments Europe, Ltd. (Ireland). You enter your payment details directly with Stripe; complete card or account details do not reach us.</p>
      <p>In this context we process the payment reference, the plan booked, the amount, the payment status and the time, together with the invoice data Stripe reports back to us. The legal basis is Article 6(1)(b) GDPR (performance of contract) and, as regards invoices and accounting records, Article 6(1)(c) GDPR in conjunction with commercial and tax retention obligations.</p>
      <p>Stripe acts as an independent controller for the payment transaction and for meeting its own regulatory obligations; Stripe’s privacy policy applies in addition.</p>
      <h2>9. Cookies, local storage and audience measurement</h2>
      <p>We use technically necessary cookies or similar storage access only where required for a function expressly requested by you. The legal basis for access to your terminal equipment is section 25(2) TDDDG; subsequent processing of personal data is based on Article 6(1)(b) or (f) GDPR.</p>
      <h3>9.1 Our own usage and campaign measurement</h3>
      <p>To understand where the service is intelligible and where users drop out, we record our own events — for example opening the home page, starting a photo selection, completion or failure of an analysis, and downloading the result. The events are sent exclusively to our own endpoint on the same domain and stored with our provider Upstash in the EU. We do not embed any third-party counting pixels, tags or scripts for this.</p>
      <p>With an event we store a random session identifier, the device class (mobile, tablet, desktop), operating-system and browser family, the language version, a coarse size band for the number of photos selected, and — if you arrived through an advertisement we placed — the campaign markers contained in the address you called up (the so-called UTM parameters). We do <strong>not</strong> store file names, image content, location data or email addresses.</p>
      <p>This measurement does not access your terminal equipment. The session identifier exists only in your browser’s memory and ends when you close the page; it is stored neither in a cookie nor in your browser’s local storage. No consent under section 25 TDDDG and no cookie banner is therefore required. The price of this restraint is that we cannot recognise returning visitors — which is intended.</p>
      <p>Click identifiers assigned by advertising networks (such as <span className="font-mono">gclid</span> or <span className="font-mono">fbclid</span>), which may be attached to the address when you arrive through an advertisement, are neither stored nor evaluated by us.</p>
      <p>If you are signed in to your user account, we additionally associate these events with a pseudonymous identifier derived from your account identifier. This is the only way for us to see whether the service is used a second time. No such association is made while you are not signed in.</p>
      <p>The legal basis is Article 6(1)(f) GDPR. Our legitimate interest is being able to assess the intelligibility, technical quality and economics of the service in a data-minimising way without using third-party tracking services. You may object to this processing under Article 21 GDPR; please contact our privacy contact. For retention periods see section 11.</p>
      <h3>9.2 Audience measurement by Vercel</h3>
      <p>Vercel Web Analytics may be used for aggregated audience measurement in a cookieless configuration. Under our configuration, it does not create cross-device or cross-site user profiles. Reports made available to us are aggregated. The legal basis is Article 6(1)(f) GDPR; our legitimate interest is understanding usage and technical quality in a data-minimising way.</p>
      <h3>9.3 No third-party analytics or marketing services</h3>
      <p>Google Analytics, Google Ads, the Meta pixel and other non-essential analytics or marketing services are not active. We have deliberately decided against using them to evaluate our advertising campaigns and instead evaluate those through our own measurement described in section 9.1. If such services are introduced later, they will be activated only after voluntary consent and this Privacy Policy will be updated in advance.</p>
      <h2>10. Recipients and processors</h2>
      <p>Depending on the functions used, the following recipients may process data:</p>
      <p>Google Cloud EMEA Limited and Google subprocessors – AI analysis through the paid Gemini Developer API;</p>
      <p>Vercel Inc. and subprocessors – hosting, delivery, security logs and, where applicable, cookieless audience measurement;</p>
      <p>Upstash, Inc. and subprocessors – feedback, update subscriptions, abuse-prevention counters and the events of our own usage measurement under section 9.1, in the EU region;</p>
      <p>Supabase, Inc. and subprocessors – accounts, authentication and job data (see section 15);</p>
      <p>Resend, Inc. and Amazon Web Services – delivery of account and feedback emails;</p>
      <p>Stripe Payments Europe, Ltd. – payment processing once you book a paid plan (see section 8a);</p>
      <p>Dropbox – only if you use the cloud import or export; other cloud providers currently not active;</p>
      <p>IT, security, legal or public authorities where required to comply with legal obligations or establish, exercise or defend legal claims.</p>
      <p>We enter into Article 28 GDPR processing agreements with processors. Where required for third-country transfers, we rely on adequacy decisions, EU Standard Contractual Clauses and supplementary safeguards.</p>
      <h2>11. Retention periods</h2>
      <p>High-resolution originals: not sent to Google and not stored by AJ GmbH;</p>
      <p>Previews at AJ GmbH: no permanent application-database storage; processed only for the job and technically unavoidable short-term storage;</p>
      <p>Reference photos, temporary biometric feature representations and matching results at AJ GmbH: only for the active analysis job, then deleted from the application environment;</p>
      <p>Technical record of the reference-photo authority confirmation: without the reference photo, name or contact details for 30 days; longer only in a specific security, misuse or legal case;</p>
      <p>Previews and responses at Google: under current documentation, up to 55 days for security/abuse purposes unless a shorter binding zero-data-retention configuration applies;</p>
      <p>Hosting/security logs: 30 days, see section 3;</p>
      <p>Feedback/support and update subscriptions: as stated in section 8;</p>
      <p>Rounded GPS coordinates used for place naming: not stored by AJ GmbH; at the AI provider the same periods apply as for the previews;</p>
      <p>Events of our own usage measurement under section 9.1: 90 days in individual form, thereafter only in aggregated form without any session or account reference;</p>
      <p>Payment and invoice data under section 8a: for the duration of commercial and tax retention periods, as a rule up to ten years;</p>
      <p>Consent evidence for product updates and other legally relevant records: for the applicable statutory evidence and limitation periods.</p>
      <h2>12. Data security</h2>
      <p>We implement technical and organisational measures appropriate to the processing risk. These include encrypted transmission, access restrictions, separate key and permission management, data minimisation, abuse controls, logging of security-relevant events and regular provider reviews. Absolute security of transmission or storage cannot be guaranteed.</p>
      <h2>13. Your rights</h2>
      <p>Subject to statutory conditions, you have rights of access, rectification, erasure, restriction, data portability and objection. You may withdraw consent at any time with future effect. Processing carried out before withdrawal remains lawful.</p>
      <p>Send requests to the privacy contact in section 1. As we do not permanently store photos and normally do not retain identity data linked to a job, we may require additional information about the time and circumstances of the job to locate relevant data. We will not retain additional data solely to identify a person where this is not required.</p>
      <p>You also have the right to lodge a complaint with a supervisory authority. The authority normally responsible for AJ GmbH is:</p>
      <p>The Hessian Commissioner for Data Protection and Freedom of Information</p>
      <p>Wilhelmstraße 7</p>
      <p>65185 Wiesbaden</p>
      <p>Germany</p>
      <h2>14. Objection to processing under Article 6(1)(f) GDPR</h2>
      <p>You may object at any time, on grounds relating to your particular situation, to processing based on Article 6(1)(f) GDPR. We will then cease processing unless we demonstrate compelling legitimate grounds that override your interests, rights and freedoms or the processing is required to establish, exercise or defend legal claims.</p>
      <h2>15. User Account and Registration</h2>
      <p>When you create a user account, we process your email address, your encrypted password, the selected language (locale setting), and the timestamp and record of consent given to this Privacy Policy and the Terms of Use. The legal basis is Article 6(1)(b) GDPR (performance of contract).</p>
      <h3>15.1 Anonymous account when starting an analysis</h3>
      <p>Every analysis technically runs against a named job so that photo volumes, allowances and results can be assigned unambiguously. If you start an analysis without being signed in, we automatically create an <strong>anonymous account</strong> for this. No contact details are collected: we store only a random identifier, the time, the marker indicating anonymity and the technical data belonging to the job.</p>
      <p>The legal basis is Article 6(1)(b) GDPR; without this assignment the job you initiated cannot be carried out. An anonymous account does not allow sign-in from another device and is lost when you end the browser session. We delete anonymous accounts and the associated job data on a routine basis, at the latest 90 days after the last job. If you register later, you can continue your job with the new account.</p>
      <h3>15.2 Account and usage measurement</h3>
      <p>While you are signed in, we associate the events described in section 9.1 with a pseudonymous identifier derived from your account identifier. We do not build profiles of individual users from this; we evaluate only how often the service is used a second time overall.</p>
      <p>We use Supabase (Supabase Inc., 970 Trestle Glen Rd, Oakland, CA 94610, USA) as a processor for authentication and profile data storage. Supabase hosts data on servers in the EU region Frankfurt (AWS eu-central-1). We have concluded a data processing agreement with Supabase under Article 28 GDPR; EU Standard Contractual Clauses provide the basis for transfers to the USA.</p>
      <p>Account data is stored for as long as the account exists. You can delete your account at any time; upon deletion your data will be permanently removed within 30 days. You may exercise your rights of access, rectification and erasure at any time through our privacy contact.</p>
      <h2>16. Changes to this Privacy Policy</h2>
      <p>We update this Privacy Policy when functions, providers or the law change. The version published on the website applies. We will not implement material changes requiring new consent without obtaining that consent.</p>
    </>
  );
}

export default async function PrivacyPage({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      <header className="border-b border-zinc-200 dark:border-zinc-800">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 flex items-center justify-between h-14">
          <Link href={`/${locale}`} className="text-lg font-bold text-indigo-600">{brandName(locale)}</Link>
          <BackButton locale={locale} />
        </div>
      </header>
      <main className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-10 text-zinc-800 dark:text-zinc-200 leading-relaxed [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:mb-4 [&_h2]:mt-8 [&_h2]:mb-2 [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-zinc-900 dark:[&_h2]:text-zinc-100 [&_h3]:mt-6 [&_h3]:mb-1 [&_h3]:font-semibold [&_p]:mb-3 [&_p]:text-sm">
        {locale === 'de' ? <GermanBody /> : <EnglishBody />}
        <div className="mt-10 border-t border-zinc-200 dark:border-zinc-800 pt-6">
          <BackButton locale={locale} />
        </div>
      </main>
    </div>
  );
}
